config/routes.rb
SampleApp::Application.routes.draw do
  resources :comment_votes

  resources :post_votes

  resources :comments

  resources :posts do
    resources :comments
    resources :post_votes
  end

  resources :categories

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match 'posts/add_vote' => 'posts#add_vote'
  post 'posts/add_vote'

  match 'post_votes/show', to: 'post_votes#show'

  root  :to => "static_pages#home"
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match 'posts/search',:to => 'posts#search'

  match 'report' => 'users#report', :as => :report

  match ':controller(/:action(/:id))(.:format)'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :comments_count, :content, :name, :tag, :category_id, :user_id

  validates :content, :presence=>true
  validates :name, :presence=>true
  validates :tag, :presence=>true
  #validates :comments_count, :presence=>true
  #validates :category, :presence=>true
  validates :category_id, :presence=>true
  #validates :user_id, :presence=>true

  has_many :comments , :dependent => :destroy
  has_many :post_votes , :dependent => :destroy

  belongs_to :category
  belongs_to :user
  #has_many :comments, :dependent => :destroy
  #has_many :votes, :dependent => :destroy

  def self.find_by_content(content)
    #Post.all(:conditions => ["message like ?", "%#{content}%"])
    Post.where("content LIKE ?", "%#{content}%" )
  end

  def self.find_by_user_id(user_id)
    Post.all(:conditions => {:user_id => user_id})
  end

  def self.find_by_category_id(category_id)
    Post.all(:conditions => {:category_id => category_id})
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    @post.user_id = current_user.id
    #@post = @user.posts.create(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def add_vote
    @post = Post.find(params[:id])
    @owner= @post.user_id

    if(@post.user_id==current_user.id)
      flash[:notice] = "You cannot vote for your own post"

    elsif (PostVote.count_by_sql("select count(*) from post_votes where user_id=#{current_user.id} and post_id = #{@post.id}") == 1 )
      flash[:notice] = "You have already voted for this post"

    end



    if(@owner!=current_user.id)
      if PostVote.count_by_sql("select * from post_votes where user_id=#{current_user.id} and post_id=#{params[:id]}")==0
        @post_vote=PostVote.new
        @post_vote.user_id=current_user.id
        @post_vote.post_id=params[:id]
        @post_vote.save
        redirect_to(:controller=>'posts', :action=> 'index')
      else
        redirect_to(:controller=>'posts', :action=> 'index')
      end
    else
      redirect_to(:controller=>'posts', :action=> 'index')
    end

  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def search
    @search = params[:search]
    if @search == ""
      flash[:notice] = "Search terms cannot be blank!"
      redirect_to root_path
    else

      @results = Post.find_by_content(@search)

      @posts = Post.where("name LIKE ?", "%#{params[:search]}%")
      @posts.each do |p|
          @results << p
      end

      @posts = Post.where("tag LIKE ?", "%#{params[:search]}%")
      @posts.each do |p|
        @results << p
      end

      @user = User.where("name LIKE ?", "%#{params[:search]}%")
      @user.each do |u|
        @post_user = Post.find_by_user_id(u.id)
        @post_user.each do |p|
          @results << p
        end
      end
      @cats = Category.where("title LIKE ?", "%#{params[:search]}%")
      @cats.each do |c|
        @post_cat = Post.find_by_category_id(c.id)
        @post_cat.each do |p|
          @results << p
        end
      end

      @results = @results.sort.uniq

    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def can_vote?(post_id)
    @votes = PostVote.all(:conditions => {:post_id => post_id})
    @votes.each do |v|
      if v.user_id == session[:user_id]
        return false
      end
    end
    return true
  end

  def num_votes(post_id)
    @votes = PostVote.all(:conditions => {:post_id => post_id})
    @votes.count
  end

  def get_votes(post_id)
    @votes = PostVote.all(:conditions => {:post_id => post_id})
  end

  def has_voted?(post_id)
    if PostVote.all(:conditions => {:post_id => post_id, :user_id => current_user})
      return true
    else
      return false
    end
  end
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :name %>
    <%= f.label :Category %>
    <%= select("post", "category_id", Category.find(:all).collect{ |c| [ c.title, c.id] }) %>
    <%#= f.label :category_id %>
    <%#= select("post", "category_id", Category.all.collect{ |c| [ c.title, c.id] }) %>
  </div>

    <div class="field">
    <%= f.label :Content %><br />
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :Tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_votes.html.erb
<%
    votes_count = num_votes(post.id)

    if votes_count == 1
     if can_vote?(post.id)
       output = "One person voted for this post"
     else
       output = "You voted for this post"

     end

    else if can_vote?(post.id)
      output = "#{votes_count} people voted for this post"
    else
      output = "You and #{votes_count-1} other people voted for this post"
    end
    end
%>
<p><%= output %></p>
<p><%#= link_to output, {:controller => :post_votes, :action => :show, :id => post.id} %></p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div style = "margin-left: 40%; margin-top: 2%">
  <% if signed_in? %>
    <%= button_to 'Add new Post', new_post_path, :class => 'btn btn-xs btn-primary' %>
      <%end%>
</div>

<br/>

<ol class="posts">
  <% @posts.reverse.each do |post| %>
      <li <% if @posts.first == post %> class="first" <% end %>>

        <div class="post_message_container">
          <%@post_user = post.user_id%>
          <%@post_owner =''%>
          <% if  @post_user == 999 %>
              <% @post_owner ='Anonymous user'  %>
          <%else%>
              <% @post_owner =post.user.name  %>
          <%end%>
          <h3> <%= link_to @post_owner, post.user %>
            <%#
              = link_to post.user.name, post.user %></h3>
          <h4><%= link_to post.name, post %>  </h4>


          <%= link_to post.content, post %>


          <div class="time_ago">
            <%= time_ago_in_words(post.created_at)%> ago
          </div>
          #<%= "#{post.category.title}" %>
          <%# user3 = current_user %>


          <% if signed_in? %>
          <div>
            <% if ((post.user_id==current_user.id)|| current_user.admin==2 || (current_user.admin==1&&post.user_id!=1)) %>

                <%# if ((post.user_id==1)&& current_user.admin==2 ) %>


          <div style="float:left;">
              <%# if post.user.id == user3.id || current_user.admin == 1%>

            <%= button_to "Delete", post, :method => :delete, data: {confirm: "Do you want to delete the post ?"}, :class => 'btn btn-default btn-xs'%>
              <%# end %>
            </div>
            <%# if post.user.id == session[:user_id] %>
                <div style="float:left;">
                  <%= button_to "Edit", edit_post_path(post), :method => :get, :class => 'btn btn-default btn-xs'%>
                </div>
            <%# end %>
                <% end %>

                <% if can_vote?(post.id) && has_voted?(post.id)%>
                    <div style="float:left;">
                      <%= button_to 'Vote', {:controller => 'posts', :action => 'add_vote' , :id => post.id}, {:class => 'btn btn-default btn-xs'}%>
                    </div>
                <% end %>
                <div style="float:left;">
                  <%= button_to "Comment", post , :class => 'btn btn-default btn-xs' %>
                </div>
                <div style="clear:both;">
                </div>
                </div>
            <%# end %>
            <p>
              <%= render :partial => 'posts/votes', :locals => {:post => post} %>
            </p>


            </div>
        <div class="clear"></div>
      </li>
  <%end%>
  <%end%>
</ol>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<%= link_to "Back", :back %>
<ol id="posts_list">
  <% @results.reverse.each do |post| %>
      <li class="first">
        <div class="post_message_container">
          <h3>
          <%# if logged_in? %>
                <%#= link_to post.user.username, post.user %>
           <%# else %>
          <% if post.user != nil %>
            <%= post.user.name%>
          <%else%>
            Anonymous User
          <%end%>
           <%# end %>
          </h3>
          <% #if logged_in? %>
                <%#= link_to post.message, post %>
          <%# else %>

            <h4><%= link_to post.name, post %>  </h4>


          <%=  post.content%>  <br/>
          Tag : <%=  post.tag%>
          <% #end %>
          <div class="time_ago">
            <%= distance_of_time_in_words_to_now(post.created_at)%> ago
          </div>
          <h4>
            Category :<%= "#{post.category.title}" %>

          </h4>

        </div>
        <div class="clear"></div>
      </li>
      </br>
      </br>

  <%end%>
</ol>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<br>

<h3> Post Details</h3>
     <br>
<br>
<p>
  <h4>
  <b>Title:</b>
  </h4>
  <%= @post.name %>
</p>
 <br>
<p>
  <h4>
  <b>Content:</b>
  </h4>
  <%= @post.content %>
</p>
<br>


<p><h4>
  <b>Tag:</b>
</h4>
  <%= @post.tag %>
</p>
<br>


<%# if @post.user_id != current_user.id %>
    <%# if PostVote.count_by_sql("select count(*) from post_votes where user_id=#{current_user.id} and post_id = #{@post.id}") == 0 %>

        <%#= button_to 'Vote', :controller => 'posts', :action => 'add_vote' , :id => @post.id %>
    <%# end %>
<%#end %>



<%#= button_to 'Unvote', :controller => post, :action => :dec_vote%>

<h3>Comments</h3>
<table border=0>
<% @post.comments.each do |comment| %>
      <% @num1_votes = 0 %>
      <% @num1_votes = CommentVote.count_by_sql("select count(*) from comment_votes where comment_id=#{comment.id}") %>

          <tr>

            <td><%= comment.comment %></td>
            <% if signed_in? %>
            </t>
            <td><%= link_to '| Show ', comment %></td>
            </t>
            <%# if (comment.user_id==current_user.id)%>
                <% if ((comment.user_id==current_user.id)|| current_user.admin==2 || (current_user.admin==1&&comment.user_id!=1)) %>

          <td><%= link_to '| Edit ', edit_comment_path(comment) %></td>
                <td><%= link_to '| Delete ', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% else %>
                <td>| Edit</td>
                <td>| Delete</td>
            <% end %>

            <td><%= "| Number of votes :#{@num1_votes}" %></td>


            <% if comment.user_id != current_user.id %>
                <% if CommentVote.count_by_sql("select count(*) from comment_votes where user_id=#{current_user.id} and comment_id = #{comment.id}") == 0 %>

                    <td><%= link_to '| Vote', :controller => 'comments', :action => 'add_c_vote' , :id => comment.id %></td>
                    <% else %>
                    <td>| Vote</td>

          <% end %>
            <% else %>
                <td>| Vote</td>
            <% end %>


            <%# if can_vote?(comment.id) && has_voted?(comment.id)%>
     <%#= button_to 'Vote', {:controller => 'comments', :action => 'add_c_vote' , :id => comment.id}, {:class => 'btn btn-default btn-xs'}%>

            <%# end %>

            <%# if (comment.user_id==current_user.id)%>
                <%#= link_to 'Edit', edit_comment_path(comment) %>
                <%#= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%# end %>
            <%end%>
          </tr>

      <% end %>
  <br>
    </table>
    </p>


<br>
<br>
<% if signed_in? %>
    <h3>Add a comment:</h3>
    <%= form_for([@post, @post.comments.build]) do |f| %>

        <p>
          <%= f.label :body %><br />
          <%= f.text_area :comment %>
        </p>
        <p>
          <%= f.submit %>
        </p>
    <% end %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>
<%#= link_to 'Show comments', :controller =>'comments', :action => 'show', :post_id =>(@post.id)'%>
<%#= link_to " Show Comments" , :controller => 'comments' , :action => 'show' %>
<%#= link_to " New Comment" , :controller => 'comments' , :action => 'new' %>